
[package]
name = "rst-cli"
description = "The RSTransfer command-line interface"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rst"
path = "main.rs"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
rst-core = { path = "../rst-core" }
