name: Bug report
description: Create a new bug report.
title: "[BUG]: <title>"
labels: ["bug"]
body:
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Issue Description
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false