name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable  # Use the latest stable version of Rust

      - name: Install required toolchain for Windows
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup component add rust-src

      - name: Build for Windows
        run: |
          cd rst-cli
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Windows executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: ./target/x86_64-pc-windows-gnu/release/rst.exe
